const builtInElements: {
  [element: string]: boolean;
} = {
  view: true,
  text: true,
  button: true,
  block: true,
  'scroll-view': true,
  swiper: true,
  'swiper-item': true,
  'movable-area': true,
  'movable-view': true,
  'cover-view': true,
  icon: true,
  'rich-text': true,
  progress: true,
  checkbox: true,
  form: true,
  input: true,
  label: true,
  picker: true,
  'picker-view': true,
  radio: true,
  slider: true,
  switch: true,
  textarea: true,
  template: true,
  navigator: true,
  audio: true,
  image: true,
  camera: true,
  video: true,
  'live-player': true,
  'live-pusher': true,
  map: true,
  canvas: true,
  'open-data': true,
  'web-view': true,
  'radio-group': true,
  slot: true,
  wxs: true,
  'checkbox-group': true,
  loading: true
};

export default builtInElements;
