const builtInElements: {
  [element: string]: number;
} = {
  view: 1,
  text: 1,
  button: 1,
  block: 1,
  'scroll-view': 1,
  swiper: 1,
  'swiper-item': 1,
  'movable-area': 1,
  'movable-view': 1,
  'cover-view': 1,
  icon: 1,
  'rich-text': 1,
  progress: 1,
  checkbox: 1,
  form: 1,
  input: 1,
  label: 1,
  picker: 1,
  'picker-view': 1,
  radio: 1,
  slider: 1,
  switch: 1,
  textarea: 1,
  template: 1,
  navigator: 1,
  audio: 1,
  image: 1,
  camera: 1,
  video: 1,
  'live-player': 1,
  'live-pusher': 1,
  map: 1,
  canvas: 1,
  'open-data': 1,
  'web-view': 1,
  'radio-group': 1,
  slot: 1,
  wxs: 1,
  'checkbox-group': 1,
  loading: 1
};

export default builtInElements;
